run_parameters = {}
run_parameters['WANDB_NAME']            = 'AALS for CP'
run_parameters['WANDB_TEAM']            = 'skoltech_optimization'
run_parameters['WANDB_GROUP']           = 'Debugging line search'
run_parameters['N_EXPERIMENTS']         =  3
run_parameters['SEEDS']                 = range(999, 999-run_parameters['N_EXPERIMENTS'], -1)
run_parameters['DIM']                   =  30
run_parameters['RANK']                  =  20
run_parameters['MODE']                  =  'random'
run_parameters['REGULARIZATION_COEF']   =  0
run_parameters['NOISE']                 = 1e-5
run_parameters['N_ITER']                =  500
run_parameters['LIST_OF_METHODS']       =  ['AALS', 'ALS']