run_parameters = {}
run_parameters['WANDB_NAME']            = 'AALS for CP'
run_parameters['WANDB_TEAM']            = 'skoltech_optimization'
run_parameters['WANDB_GROUP']           = 'Debug runs'
run_parameters['N_EXPERIMENTS']         =  1
run_parameters['SEEDS']                 = range(999, 999-run_parameters['N_EXPERIMENTS'], -1)
run_parameters['DIM']                   =  10
run_parameters['RANK']                  =  4
run_parameters['MODE']                  =  'random'
run_parameters['REGULARIZATION_COEF']   =  0
run_parameters['NOISE']                 = 1e-5
run_parameters['N_ITER']                =  100
run_parameters['LIST_OF_METHODS']       =  ['ALS', 'AALS']